-- ============================================================
-- Manual battery charge observation for KPCL0036
-- ============================================================
-- Seed row used to keep a real observed charging window for
-- future battery calculations and reporting.
--
-- Observation:
--   KPCL0036 charged from 2026-04-01 08:36 to 2026-04-01 12:42
--   local time (America/Santiago), for a total of 4h06m.
-- ============================================================

with device_ctx as (
  select
    d.id as device_uuid,
    d.device_id as device_code,
    d.device_type,
    d.status as device_status,
    d.device_state
  from public.devices d
  where d.device_id = 'KPCL0036'
  limit 1
)
insert into public.device_battery_cycles (
  device_uuid,
  device_code,
  device_label,
  device_type,
  device_status,
  device_state,
  cycle_status,
  cycle_start_at,
  charging_start_at,
  full_charge_at,
  cycle_end_at,
  battery_level_at_start,
  battery_level_at_full_charge,
  battery_level_at_end,
  battery_voltage_at_start,
  battery_voltage_at_full_charge,
  battery_voltage_at_end,
  battery_state_at_start,
  battery_state_at_full_charge,
  battery_state_at_end,
  battery_source_at_start,
  battery_source_at_full_charge,
  battery_source_at_end,
  readings_count,
  charging_samples,
  battery_only_samples,
  charging_duration_seconds,
  battery_only_duration_seconds,
  total_duration_seconds,
  battery_component_code,
  charger_component_code,
  battery_capacity_mah,
  battery_nominal_voltage_v,
  estimated_charge_current_ma,
  estimated_full_charge_hours,
  battery_bom_context,
  summary,
  notes,
  created_at,
  updated_at
)
select
  d.device_uuid,
  d.device_code,
  d.device_code as device_label,
  d.device_type,
  d.device_status,
  d.device_state,
  'full',
  timestamptz '2026-04-01 08:36:00-03',
  timestamptz '2026-04-01 08:36:00-03',
  timestamptz '2026-04-01 12:42:00-03',
  timestamptz '2026-04-01 12:42:00-03',
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  0,
  0,
  0,
  14760,
  null,
  14760,
  'BATT_LIPO_602025',
  'CHG_TP4056_TYPEC',
  250,
  3.7,
  null,
  null,
  jsonb_build_object(
    'source', 'manual_observation',
    'device_code', d.device_code,
    'window_start', '2026-04-01T08:36:00-03:00',
    'full_charge_at', '2026-04-01T12:42:00-03:00',
    'duration_seconds', 14760,
    'duration_minutes', 246,
    'duration_hhmm', '04:06:00',
    'battery_telemetry', 'not_available',
    'calculation_note', 'Use as a planning baseline until real battery telemetry is available.'
  ),
  jsonb_build_object(
    'source', 'manual_observation',
    'observed_window_start', '2026-04-01T08:36:00-03:00',
    'observed_full_charge_at', '2026-04-01T12:42:00-03:00',
    'observed_duration_seconds', 14760,
    'observed_duration_minutes', 246,
    'observed_duration_hhmm', '04:06:00',
    'device_code', d.device_code,
    'notes', 'Manual cycle recorded for future battery calculations.'
  ),
  'KPCL0036 manual full-charge observation. The device took 4h06m to reach full charge from 08:36 to 12:42 local time.',
  now(),
  now()
from device_ctx d
on conflict (device_uuid, cycle_start_at)
do update set
  device_code = excluded.device_code,
  device_label = excluded.device_label,
  device_type = excluded.device_type,
  device_status = excluded.device_status,
  device_state = excluded.device_state,
  cycle_status = excluded.cycle_status,
  charging_start_at = excluded.charging_start_at,
  full_charge_at = excluded.full_charge_at,
  cycle_end_at = excluded.cycle_end_at,
  battery_level_at_start = excluded.battery_level_at_start,
  battery_level_at_full_charge = excluded.battery_level_at_full_charge,
  battery_level_at_end = excluded.battery_level_at_end,
  battery_voltage_at_start = excluded.battery_voltage_at_start,
  battery_voltage_at_full_charge = excluded.battery_voltage_at_full_charge,
  battery_voltage_at_end = excluded.battery_voltage_at_end,
  battery_state_at_start = excluded.battery_state_at_start,
  battery_state_at_full_charge = excluded.battery_state_at_full_charge,
  battery_state_at_end = excluded.battery_state_at_end,
  battery_source_at_start = excluded.battery_source_at_start,
  battery_source_at_full_charge = excluded.battery_source_at_full_charge,
  battery_source_at_end = excluded.battery_source_at_end,
  readings_count = excluded.readings_count,
  charging_samples = excluded.charging_samples,
  battery_only_samples = excluded.battery_only_samples,
  charging_duration_seconds = excluded.charging_duration_seconds,
  battery_only_duration_seconds = excluded.battery_only_duration_seconds,
  total_duration_seconds = excluded.total_duration_seconds,
  battery_component_code = excluded.battery_component_code,
  charger_component_code = excluded.charger_component_code,
  battery_capacity_mah = excluded.battery_capacity_mah,
  battery_nominal_voltage_v = excluded.battery_nominal_voltage_v,
  estimated_charge_current_ma = excluded.estimated_charge_current_ma,
  estimated_full_charge_hours = excluded.estimated_full_charge_hours,
  battery_bom_context = excluded.battery_bom_context,
  summary = excluded.summary,
  notes = excluded.notes,
  updated_at = now();
